version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACED_AT_RUNTIME"
        LoadBalancerInfo:
          ContainerName: "strapi"
          ContainerPort: 1337
